name: License Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-license-check:
    name: Go License Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          
      - name: Install license-lint
        run: |
          go install istio.io/tools/cmd/license-lint@v1.26.1
          
      - name: Run Go license check
        run: |
          cd go
          license-lint --config .license-lint.yaml 